### PR TITLE
feat: update outdated pacakges and imports for langchain and openai deps

### PR DESCRIPTION
**Pull request by VeVarunSharma**
## What kind of change does this PR introduce?

**Bug fix!!**  🚀  🕺🏽  💃🏽 

This PR enables the langchain-chatbot-demo to be working again. It was broken because there was substantive package dependency updates from langchain, as well as some old LLM model deprecations from OpenAI.

Everything is now working as intended ✅  

## What is the current behavior?
This PR fixes the issues outlined here:
https://github.com/supabase-community/langchain-chatbot-demo/issues/9

## What is the new behavior?

As outlined in the linked Bug issue #9  sub-issue 1 with the chat functionality is now working, and sub-issue 2 with issues storing the embeddings from the crawler into supabase is now fixed! 🚀 

## Additional context

I had came across this langchain demo via the Langchain YouTube Tutorial: [here](https://www.youtube.com/watch?v=Tt45NrVIBn8)

For Sub-issue 1 the chat functionality is working well again!

Chat functionality working:
image

image

For Sub-issue 2 the storing of embeddings via the crawler to supabase is working well again!

image

Crawler + conversion to embeddings, and storing to supabase is working:
image

### CODE REVIEW

**Comment by VeVarunSharma** [comment]
Just requesting a review here from someone at the supa community!
maybe @thorwebdev? :)

**Comment by amanuelz91** [comment]
> Just requesting a review here from someone at the supa community! maybe @thorwebdev? :)

Much appreciated @print-VarunSharma! This got things working for me!

**Comment by VeVarunSharma** [comment]
> > Just requesting a review here from someone at the supa community! maybe @thorwebdev? :)
> 
> 
> 
> Much appreciated @print-VarunSharma! This got things working for me!

Amazing!! 😎😁 I'm glad that worked for you and happy to help :)

**Comment by thorwebdev** [comment]
Holy moly, sorry for the crazy delay, this slipped through the cracks 🙈 Thank you 💚

**Comment by VeVarunSharma** [comment]
> Holy moly, sorry for the crazy delay, this slipped through the cracks 🙈 Thank you 💚

No worries at all! This is fantastic this is merged up now for the community! 🕺🏽 💃🏽

**Pull request merged**
